name: rmg3
channels:
  - defaults
  - rmg
  - rdkit
  - cantera
  - pytorch
  - conda-forge
dependencies:
  - cairo >= 1.16.0
  - cairocffi
  - cantera >=2.4.0
  - cclib
  - chemprop
  - coolprop
  - coverage
  - cython >=0.29.21
  - ffmpeg
  - gprof2dot
  - graphviz
  - h5py
  - jinja2
  - jupyter
  - lpsolve55
  - markupsafe
  - matplotlib >=3.2.2
  - mopac
  - mpmath
  - muq2
  - networkx
  - nose
  - numdifftools
  - numpy >=1.15.4
  - openbabel
  - pandas
  - psutil
  - pydas >=1.0.2
  - pydot
  - pydqed >=1.0.1
  - pymongo
  - pyparsing
  - pyrdl
  - python >=3.7.7
  - pyyaml
  - quantities
  - rdkit >=2020.03.3.0
  - scikit-learn
  - scipy >=1.5.0
  - symmetry
  - xlrd
  - xlwt
  - openbabel >=3.1.1
  - dnspython
