#/usr/bin/bash
#PBS -l select=1:ncpus=1:mpiprocs=1

cd /home/hpc/ypli/jianyi/AutomaticReactionDiscovery/script
echo "=========================================================="
echo "Starting on : $(date)"
echo "Running on node : $(hostname)"
echo "Current directory : $(pwd)"
echo "Current job ID : $PBS_JOBID"
#echo "ARRAY_ID: $PBS_ARRAYID"
echo "=========================================================="

source ~/.bashrc
conda activate rmg3

python ard.py input.txt
conda deactivate
