#/usr/bin/bash
#PBS -l select=1:ncpus=2:mpiprocs=2

cd /home/guest/guest94/jianyi/AutomaticReactionDiscovery

echo "=========================================================="
echo "Starting on : $(date)"
echo "Running on node : $(hostname)"
echo "Current directory : $(pwd)"
echo "Current job ID : $PBS_JOBID"
#echo "ARRAY_ID: $PBS_ARRAYID"
echo "=========================================================="

source ~/.bashrc_qchem
conda activate rmg_env

python ./ard.py input.txt
conda deactivate
