irc:
 type: eulerpc              # Similar to EulerPC from Gaussian
endopt:
 fragments: True            # Detect fragments at the end of the IRC and optimize them separately.
 do_hess: True
 thresh: gau_tight
calc:
 type: orca
 keywords: B3LYP D3BJ def2-SVP rijcosx def2/J def2-svp/C
 blocks: "%scf maxiter 500 end"
 pal: 4
 charge: 0
 mult: 1
geom:
 type: cart
 fn: ts_geo.xyz